import type { CapabilityToolName } from "../tools/tool-manifest.js";

export type ToolAccessMode = "public" | "session" | "role";

export interface ToolAccessPolicyEntry {
  mode: ToolAccessMode;
}

export const TOOL_ACCESS_POLICY: Record<CapabilityToolName, ToolAccessPolicyEntry> = {
  status: { mode: "public" },
  capabilities: { mode: "public" },
  schema: { mode: "public" },
  get_code_pack: { mode: "public" },
  get_change_pack: { mode: "public" },
  get_issue_pack: { mode: "public" },
  search_remote_instances: { mode: "public" },
  run_workflow: { mode: "public" },
  propose_patch: { mode: "role" },
  propose_note: { mode: "role" },
  register_agent: { mode: "public" },
  agent_status: { mode: "public" },
  broadcast: { mode: "role" },
  send_coordination: { mode: "role" },
  poll_coordination: { mode: "session" },
  claim_files: { mode: "role" },
  end_session: { mode: "session" },
  request_reindex: { mode: "role" },
  list_patches: { mode: "role" },
  list_notes: { mode: "role" },
  store_knowledge: { mode: "role" },
  search_knowledge: { mode: "public" },
  query_knowledge: { mode: "public" },
  archive_knowledge: { mode: "role" },
  delete_knowledge: { mode: "role" },
  create_ticket: { mode: "role" },
  assign_ticket: { mode: "role" },
  update_ticket_status: { mode: "role" },
  update_ticket: { mode: "role" },
  list_tickets: { mode: "role" },
  search_tickets: { mode: "role" },
  get_ticket: { mode: "role" },
  comment_ticket: { mode: "role" },
  assign_council: { mode: "role" },
  submit_verdict: { mode: "role" },
  check_consensus: { mode: "role" },
  link_tickets: { mode: "role" },
  prune_stale_relations: { mode: "role" },
  unlink_tickets: { mode: "role" },
  add_protected_artifact: { mode: "role" },
  remove_protected_artifact: { mode: "role" },
  list_protected_artifacts: { mode: "role" },
  analyze_complexity: { mode: "public" },
  analyze_test_coverage: { mode: "public" },
  analyze_coupling: { mode: "public" },
  find_dependency_cycles: { mode: "public" },
  suggest_actions: { mode: "public" },
  suggest_next_work: { mode: "role" },
  lookup_dependencies: { mode: "public" },
  trace_dependencies: { mode: "public" },
  export_audit: { mode: "role" },
  run_simulation: { mode: "role" },
  run_optimization: { mode: "role" },
  create_loop: { mode: "role" },
  list_jobs: { mode: "role" },
  claim_job: { mode: "role" },
  update_job_progress: { mode: "session" },
  complete_job: { mode: "session" },
  release_job: { mode: "role" },
  find_references: { mode: "public" },
  create_work_group: { mode: "role" },
  update_work_group: { mode: "role" },
  add_tickets_to_group: { mode: "role" },
  remove_tickets_from_group: { mode: "role" },
  list_work_groups: { mode: "session" },
  decompose_goal: { mode: "role" },
  compute_waves: { mode: "role" },
  launch_convoy: { mode: "role" },
  advance_wave: { mode: "role" },
  get_wave_status: { mode: "session" },
  spawn_agent: { mode: "role" },
};
