export const CAPABILITY_TOOL_NAMES = [
  "status", "capabilities", "schema",
  "get_code_pack", "get_change_pack", "get_issue_pack", "search_remote_instances",
  "run_workflow",
  "propose_patch", "propose_note",
  "register_agent", "agent_status", "broadcast",
  "send_coordination", "poll_coordination",
  "claim_files", "end_session", "request_reindex",
  "list_patches", "list_notes",
  "store_knowledge", "search_knowledge", "query_knowledge", "archive_knowledge", "delete_knowledge",
  "create_ticket", "assign_ticket", "update_ticket_status", "update_ticket",
  "list_tickets", "search_tickets", "get_ticket", "comment_ticket", "assign_council", "submit_verdict", "check_consensus",
  "link_tickets", "unlink_tickets", "prune_stale_relations",
  "add_protected_artifact", "remove_protected_artifact", "list_protected_artifacts",
  "analyze_complexity",
  "analyze_test_coverage",
  "analyze_coupling",
  "find_dependency_cycles",
  "suggest_actions",
  "suggest_next_work",
  "lookup_dependencies",
  "find_references",
  "trace_dependencies",
  "export_audit",
  "run_simulation",
  "run_optimization",
  "create_loop",
  "list_jobs",
  "claim_job",
  "update_job_progress",
  "complete_job",
  "release_job",
  "create_work_group",
  "update_work_group",
  "add_tickets_to_group",
  "remove_tickets_from_group",
  "list_work_groups",
  "decompose_goal",
  "compute_waves",
  "launch_convoy",
  "advance_wave",
  "get_wave_status",
  "spawn_agent",
] as const;

export type CapabilityToolName = (typeof CAPABILITY_TOOL_NAMES)[number];
